#include<iostream>
using namespace std;
int main()
{
    int a;
    cout<<"Enter name of the person\n";
    string name;
    cin>>name;
    cout<<"Enter the gender\n";
    string gender;
    cin>>gender;
    cout<<"Enter the Age\n";
    cin>>age;
    cout<<"Enter the person city\n";
    cin>>city;
    if(a==25&&a==35)
    {
        cout<<"gender = male\n";
        cout<<"person city = metro\n";
        cout<<"output permium = 3%\n";
    }
    else if(a==)

    return 0;
}